### ISSUE TITLE
[FEAT] 공통 컴포넌트 생성

### ISSUE THREAD

**Issue by yoon-junseo** [BeforeDeadline/anbu_frontend#1]
## 설명
- 공통 컴포넌트 생성

## ToDo
- [x] tag
- [x] d-day box
- [x] 사람 아이콘
- [x] text button (Text로 버튼 모양 구현)
- [x] 친구 목록 컴포넌트
- [x] 홈 친구 목록 컴포넌트
